language: python
python:
    - "3.6"
# command to install dependencies
install:
  - pip install pylint
# command to run tests
script:
  - python -m unittest discover -v -p "*.py" pypractice
  - pylint --rcfile .pylint.rc pypractice
